### PR TITLE
Add Makefile and docker-compose.yml.

### PR DESCRIPTION
**Pull request by ryanlovett**
Also add .env to .gitignore.

### CODE REVIEW

**Comment by ryanlovett** [comment]
@andrewpbray This branch works on Linux and macOS amd64. I have not tested this yet on macOS arm64 (Apple silicon) or Windows.

You can run `make up` to pull the textbook image, prepare architecture-specific environment variable, and start the image. SSH agent forwarding works, as does reading/writing textbook files.

**Comment by ryanlovett** [comment]
@andrewpbray This works on Apple Silicon, and I've added some instructions.

**Comment by ryanlovett** [comment]
This works on Windows as well, with WSL.

**Comment by andrewpbray** [comment]
@ryanlovett I just tested this now on my intel macos and . . . seemed to work just fine!

A few things of note:

1. when I run `make up` i get some interesting feedback:

Screen Shot 2023-06-20 at 9 44 15 PM

I don't follow everything that's being done in that make file, so does this all look as expected?

2. I changed some files and made commits from within the rstudio terminal. it prompted me to set up git email and username. once i did that, it committed just fine. i stopped the container, restarted it and i was surprised by how much was saved: the terminal seemed to me in its same state, the previous commands at the R console were saved, and git remembered my email and username.

If this all seems kosher, I'll go ahead and merge this PR.

**Comment by ryanlovett** [comment]
@andrewpbray Glad to hear it worked! Yes, that output is typical of what one sees when starting this rocker image. 

I suspect git remembered your username and email because it wrote them out to your working directory. 

I believe some of the RStudio session state is being stored in cookies, but I haven’t investigated fully. You could try restarting the container and then visiting the url from a different browser. Whatever session state does persist would be in the container somewhere — probably under ~/.rstudio/. 

I think this is ready to merge. We can also think about whether we can put some of the docket related files in a sub directory, isolating them from the textbook materials.

**Comment by andrewpbray** [comment]
Thanks Ryan!

**Pull request merged**
