### PR TITLE
problem sets

### PR DESCRIPTION
**Pull request by shomurali**
Hi Andrew, could you please add the problem sets folder to main. I will update it today.

### CODE REVIEW

**Review by andrewpbray — CHANGES_REQUESTED** [review]
please revise the filename so that it is `data-foundations.qmd`

**Comment by andrewpbray** [comment]
The file name looks great. Please update with
1. one foundations prob
2. ps 3 g of g
3. ps 4 and the link to the tutorial

**Comment by shomurali** [comment]
Hi Andrew, I added problems from PS 3 and the tutorial from PS 4. I think this is enough. I changed the immigration problem to incorporate a bar chart, let me know if it looks okay. The spacing is a bit funky. What do you think?

**Comment by andrewpbray** [comment]
I made two small edits
- added some language around joint/condition/marginal to try to get more practice with that in advance of probability
- moved the review question to the end (it's a bit jarring to me to lead out with a politically charged topic).

Thanks for putting this together! I'll be up on the website momentarily. Could you please create a Gradescope Assignment?

**Review by andrewpbray — APPROVED** [review]

**Comment by shomurali** [comment]
okay, I will create a gs assignment later today. I agree with moving the immigration question since it might be a hook, or it might be a put-off.  I wasn't really thinking about that, as when I had begun copying over your problems from the spring, it was the second problem :)

**Pull request merged**
