### PR TITLE
Lab 6

### PR DESCRIPTION
**Pull request by jeremy-sanchez**

### CODE REVIEW

**Comment by jeremy-sanchez** [comment]
Added MSE and RMSE

**Comment by andrewpbray** [comment]
Hey Jeremy, looks like the notes don't render:

[https://stat20-pr.netlify.app/6-prediction/03-overfitting/notes.html](https://stat20-pr.netlify.app/6-prediction/03-overfitting/notes.html)

If you take a look at [the run](https://github.com/stat20/stat20/actions/runs/8575874939/job/23505761816), it says:

```
Error in `library()`:
! there is no package called 'rsample'
Backtrace:
 1. base::library(rsample)
```

Whenever you add a new dependency to the curriculum, it needs to be added to the description of the image that builds the website.

You can do this by adding a line to a .r file in the repo that has the description for all of the campus data hubs. I just submitted that PR here: [https://github.com/berkeley-dsep-infra/datahub/pull/5667](https://github.com/berkeley-dsep-infra/datahub/pull/5667) (you may want to bookmark that site). Once someone (often Ryan) merges the PR, it'll take about an hour before the new image will be ready to be pulled into our workflows over at Stat 20.

**Comment by andrewpbray** [comment]
Whoops, one more thing to say about that:

The process that I outlined above is to update the image that's used at stat20.datahub.berkeley.edu - that is, the packages that the students see in their RStudio. The image that we need here is stored in our own stat20 org, so I was able to make that change directly:

[https://github.com/stat20/stat20-docker/commit/c0911fec829a3ea8146fe1feb0cddd0f5bc927ff](https://github.com/stat20/stat20-docker/commit/c0911fec829a3ea8146fe1feb0cddd0f5bc927ff
)

@ryanlovett I guess this would be run reason to have both the curriculum and the students work off the same image: easier to keep track of things. Often when we add a dependency to the notes its because we'd like the students to be able to use them in assignments.

**Review by andrewpbray — APPROVED** [review]
I'm very glad you made these updates to use MSE! I remember on the cancer lab that doing comparisons based on R^2 is pretty confusing.

**Comment by ryanlovett** [comment]
@andrewpbray In the short term we could sync up the images. In the long term, we could try to find out how to make them be the same. Right now all datahub images are inside the datahub deployment and are a part of its CI. We don't have a model where course staff maintain their own image. To enable them to be the same image, I'd need to raise this with the datahub staff to see if they're okay with using images curated by others.

The gradebook deployment is *almost* like this, however it is a sidecar container, separate from the main gradebook image.

One variation on this might be for the stat20 datahub image to be jupyter-only -- essentially contain what is necessary to run on a hub, and then the stat20 sidecar image could contain quarto, RStudio, etc. That is very similar to gradebook. The stat20 sidecar image would be deployed along side stat20 to run RStudio as the default URL, and course staff could run it on their own devices as well, and it could be maintained externally. But I don't know to what extent stat20 uses jupyter and python otherwise.

Lastly, a more minimal change could be to source the list of requirements and libraries from a stat20-maintained file. So both the stat20 hub image and the stat20 development image would retrieve the equivalent of the class-libs.R file from a stat20 repo. One would have to use a git hash to make it reproducible, but then course staff would still need to update this hash on the hub image whenever the file changed.  Not entirely set and forget.

**Pull request merged**
