### PR TITLE
Stat 20 Spring 2024 Revisions

### PR DESCRIPTION
**Pull request by jeremy-sanchez**
Probability notes (Intro to Chance)

### CODE REVIEW

**Comment by andrewpbray** [comment]
@jeremy-sanchez Was this meant to be a PR into Sho's branch?

**Comment by jeremy-sanchez** [comment]
@andrewpbray Sho asked me to put up the final version on Friday night. Then she wanted to make changes after it published and did so on Saturday; this also added back elements in the notes that I removed.

**Comment by jeremy-sanchez** [comment]
It was my fault for not reviewing the PR more closely.

**Comment by jeremy-sanchez** [comment]
These elements are not part of the reading questions.

**Comment by jeremy-sanchez** [comment]
I think it would work best to merge this into sho-revise-prob.

**Comment by shomurali** [comment]
sorry :(

-----
Shobhana Murali Stoyanov
Continuing Lecturer
Department of Statistics
University of California, Berkeley

pronouns: *she/her*

**Comment by shomurali** [comment]
What do you refer to here?
-----
Shobhana Murali Stoyanov
Continuing Lecturer
Department of Statistics
University of California, Berkeley

pronouns: *she/her*

**Pull request merged**
