### PR TITLE
changed titles to match each other in ps, slides,and notes, added tra…

### PR DESCRIPTION
**Pull request by shomurali**
…nsition sentences and moved stuff around a bit.

### CODE REVIEW

**Comment by shomurali** [comment]
no need to merge yet, work in progress

**Comment by shomurali** [comment]
Not ready to be merged, ideas in code incomplete.

**Review by andrewpbray — APPROVED** [review]

**Comment by andrewpbray** [comment]
You forgot the `_config.yml`!

I'll add it to `main` directly.

**Comment by shomurali** [comment]
I didn't forget the _config.yml :( 
Wasn't quite sure what to do. Will check with you tomorrow.

**Pull request merged**
