### PR TITLE
Revise generalization

### PR DESCRIPTION
**Pull request by andrewpbray**

### CODE REVIEW

**Comment by andrewpbray** [comment]
@shomurali could you please take a look at the notes to see about the remove / revisions to the normal dist section (in light of the movement to the prob section).

**Comment by shomurali** [comment]
Starting at line 232 ("Observe that...") do you want to mention the CLT since they have seen it. Or ask: "Why do you think the sampling distribution of the sample mean is bell-shaped?"

**Comment by shomurali** [comment]
line 356 etc: I think here it would be beneficial to remind them of the empirical rule and how we get the 95% with 1.96 or roughly 2 SEs out from the mean in either direction. Maybe even a small picture? And is it possible to link to the section in the Normal approx notes?

**Comment by shomurali** [comment]
Chunk beginning at line 429: do you want to mess with binwidth to avoid the missing bar in the center of the sampling distribution?

**Comment by shomurali** [comment]
As always, very nicely written notes, Andrew. Please see my comments.

**Pull request merged**
