### PR TITLE
removed worksheet so it doesn't show up

### PR DESCRIPTION
**Pull request by shomurali**

### CODE REVIEW

**Review by andrewpbray — COMMENTED** [review]
@shomurali instead of just deleting it, could you do what we did previously and rename it to `archive/_old-worksheet.qmd`?

**Comment by shomurali** [comment]
Oh, yes! I will do that. Sorry, forgot.

**Comment by shomurali** [comment]
Could you accept the pr now?

**Comment by andrewpbray** [comment]
thansk!

**Pull request merged**
