### PR TITLE
fixed typo in PS 4 bonus question

### PR DESCRIPTION
**Pull request by shomurali**

### CODE REVIEW

**Comment by andrewpbray** [comment]
If you click on "files changed" it looks like this is a correction to the coin flipping activity?

**Comment by shomurali** [comment]
sorry, I I thought I had pushed the change to the file scope-box-model. Could you check now?

**Comment by andrewpbray** [comment]
Looks great - thanks!

**Comment by andrewpbray** [comment]
Btw, it looks like this typo fix didn't actually fix the typo. No worries, though, I'll fix it!

[https://github.com/stat20/course-materials/pull/110/files](https://github.com/stat20/course-materials/pull/110/files)

**Pull request merged**
